name: test-build-deploy

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/cortexproject/build-image:update-golang-1.14.9-eb0c8d4d2
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - run: echo "$(pwd)"
      - run: echo "$(ls -al)"
      - run: echo $GOPATH
      - name: Lint
        run: make BUILD_IN_CONTAINER=false lint
      - name: Check protos are consistent.
        run: make BUILD_IN_CONTAINER=false check-protos
      # - name: Check generated documentation is consistent.
      #   run: make BUILD_IN_CONTAINER=false check-doc
      # - name: Check white noise.
      #   run: make BUILD_IN_CONTAINER=false check-white-noise
