name: update-verison # this workflow is run post release to update the .github/workflows/latest-version file
on:
  release:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+** # Tag filters not as strict due to different regex system on Github Actions
jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Update latest-version file
        run: $IMAGE_TAG > latest-version
        env:
          IMAGE_TAG: ${{ github.event.release.tag_name }}
        working-directory: .github/workflows